services:
  - type: web
    name: celebrity-look-alike
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16.14.0
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
